#!/usr/bin/env bash
set -euo pipefail

if [[ "$(uname -s)" == "Darwin" ]]; then
	default_user_data_dir="${HOME}/Library/Application Support/Superset-DoyDeck-Dev"
else
	default_user_data_dir="${HOME}/.doydeck-superset-dev/electron-user-data"
fi

export DOYDECK_DEV_MODE="${DOYDECK_DEV_MODE:-1}"
export SUPERSET_WORKSPACE_NAME="${SUPERSET_WORKSPACE_NAME:-doydeck-dev}"
export SUPERSET_HOME_DIR="${SUPERSET_HOME_DIR:-${HOME}/.doydeck-superset-dev}"
export DOYDECK_SUPERSET_USER_DATA_DIR="${DOYDECK_SUPERSET_USER_DATA_DIR:-${default_user_data_dir}}"
export DESKTOP_NOTIFICATIONS_PORT="${DESKTOP_NOTIFICATIONS_PORT:-51742}"
export SUPERSET_SKIP_AGENT_HOOKS="${SUPERSET_SKIP_AGENT_HOOKS:-1}"
export DOYDECK_SKIP_AGENT_HOOKS="${DOYDECK_SKIP_AGENT_HOOKS:-1}"
export SKIP_ENV_VALIDATION="${SKIP_ENV_VALIDATION:-1}"

# Keep telemetry disabled for the safe dev profile unless explicitly overridden.
export NEXT_PUBLIC_POSTHOG_KEY="${NEXT_PUBLIC_POSTHOG_KEY:-}"
export SENTRY_DSN_DESKTOP="${SENTRY_DSN_DESKTOP:-}"

cat <<EOF
[doydeck-safe-dev] launch profile
  DOYDECK_DEV_MODE=${DOYDECK_DEV_MODE}
  SUPERSET_WORKSPACE_NAME=${SUPERSET_WORKSPACE_NAME}
  SUPERSET_HOME_DIR=${SUPERSET_HOME_DIR}
  DOYDECK_SUPERSET_USER_DATA_DIR=${DOYDECK_SUPERSET_USER_DATA_DIR}
  DESKTOP_NOTIFICATIONS_PORT=${DESKTOP_NOTIFICATIONS_PORT}
  SUPERSET_SKIP_AGENT_HOOKS=${SUPERSET_SKIP_AGENT_HOOKS}
  SKIP_ENV_VALIDATION=${SKIP_ENV_VALIDATION}
  NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY:+set}
  SENTRY_DSN_DESKTOP=${SENTRY_DSN_DESKTOP:+set}
EOF

exec bun run dev
